finalize CI

diff --git a/.github/actions/db-migrate-ephermal/action.yml b/.github/actions/db-migrate-ephermal/action.yml
--- a/.github/actions/db-migrate-ephermal/action.yml
+++ b/.github/actions/db-migrate-ephermal/action.yml
@@ -1,5 +1,5 @@
 name: Ephermal DB
-description: Create an ephermal local Postgres DB
+description: Create an ephermal local Postgres DB and migrate and deploy
 
 runs:
   using: "composite"
@@ -34,3 +34,29 @@ runs:
       shell: bash
       run: |
         pnpm --filter @rccyx/seeder seed
+
+    - name: Run fresh migrations on the ephermal database
+      shell: bash
+      run: |
+        # already using zod for validation against which DB is which, of which env, but extra paranoia won't hurt
+        if [[ "$DATABASE_URL" != *"localhost"* ]] && [[ "$DATABASE_URL" != *"127.0.0.1"* ]]; then
+          echo "❌ DATABASE_URL is not local! Aborting."
+          exit 1
+        fi
+
+        echo "Running migration reset..."
+        pnpm --filter @rccyx/db migrate:reset --force
+
+        echo "Validating migrations..."
+        pnpm --filter @rccyx/db migrate:status
+
+        # deploying migrations
+        pnpm --filter @rccyx/db migrate:deploy
+
+    - name: stop ephermal DB
+      if: always()
+      shell: bash
+      run: |
+        set -euo pipefail
+        echo "Cleaning up..."
+        pnpm --filter @rccyx/db stop
diff --git a/.github/workflows/on-workflow-call-serverless-deployment.yml b/.github/workflows/on-workflow-call-serverless-deployment.yml
--- a/.github/workflows/on-workflow-call-serverless-deployment.yml
+++ b/.github/workflows/on-workflow-call-serverless-deployment.yml
@@ -44,11 +44,16 @@ jobs:
         run: |
           if [ "${{ inputs.app }}" = "continuum" ]; then
             echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_CONTINUUM_PROJECT_ID }}" >> $GITHUB_OUTPUT
-          else
+          elif [ "${{ inputs.app }}" = "api" ]; then
+            echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_API_PROJECT_ID }}" >> $GITHUB_OUTPUT
+          elif [ "${{ inputs.app }}" = "www" ]; then
             echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_WWW_PROJECT_ID }}" >> $GITHUB_OUTPUT
+          else
+            echo "ERROR: Invalid app selection '${{ inputs.app }}'. Deployment aborted."
+            exit 1
           fi
 
-          # Common ones
+          # Common ones - only reached if the app check passes
           echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_OUTPUT
           echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_OUTPUT
 
