API overhaul 2 (#647)

diff --git a/.github/workflows/on-workflow-call-serverless-deployment.yml b/.github/workflows/on-workflow-call-serverless-deployment.yml
--- a/.github/workflows/on-workflow-call-serverless-deployment.yml
+++ b/.github/workflows/on-workflow-call-serverless-deployment.yml
@@ -3,14 +3,14 @@ name: CD / Serverless Deployment
 on:
   workflow_call:
     inputs:
-      deployment_environment:
+      environment:
         required: true
         type: string
         description: "Environment to deploy to (preview or production)"
-      app_name:
+      app:
         required: true
         type: string
-        description: "App name, either 'www' or 'blog'"
+        description: "App name, follows the folder structure of ../../packages"
 
 permissions:
   pull-requests: write
@@ -20,43 +20,50 @@ permissions:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    environment: ${{ inputs.deployment_environment }}
+    environment: ${{ inputs.environment }}
 
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
           submodules: recursive
-          token: ${{ secrets.SUBMODULE_SYNC_PAT }}
+          token: ${{ secrets.SUB_SYNC }}
 
       - uses: ./.github/actions/pnpm-install
       - uses: ./.github/actions/setup-env
         with:
           ENV_SERVICE_TOKEN: ${{ secrets.ENV_SERVICE_TOKEN }}
 
-      - name: Select Vercel Project Secrets
-        id: vercel-secrets
-        run: |
-          if [ "${{ inputs.app_name }}" = "blog" ]; then
-            echo "VERCEL_PROJECT_ID=${{ env.VERCEL_BLOG_PROJECT_ID }}" >> $GITHUB_OUTPUT
-          else
-            echo "VERCEL_PROJECT_ID=${{ env.VERCEL_WWW_PROJECT_ID }}" >> $GITHUB_OUTPUT
-          fi
-
-          # Common ones
-          echo "VERCEL_ORG_ID=${{ env.VERCEL_ORG_ID }}" >> $GITHUB_OUTPUT
-          echo "VERCEL_TOKEN=${{ env.VERCEL_TOKEN }}" >> $GITHUB_OUTPUT
-
       - uses: ./.github/actions/db-migrate
         with:
           comment_on_pr: ${{ github.event_name == 'pull_request' && 'yes' || 'no' }}
 
+        # hardcored part
+      - name: Select Vercel Project Secrets
+        id: vercel-secrets
+        run: |
+          if [ "${{ inputs.app }}" = "continuum" ]; then
+            echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_CONTINUUM_PROJECT_ID }}" >> $GITHUB_OUTPUT
+          elif [ "${{ inputs.app }}" = "api" ]; then
+            echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_API_PROJECT_ID }}" >> $GITHUB_OUTPUT
+          elif [ "${{ inputs.app }}" = "www" ]; then
+            echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_WWW_PROJECT_ID }}" >> $GITHUB_OUTPUT
+          else
+            echo "ERROR: Invalid app selection '${{ inputs.app }}'. Deployment aborted."
+            exit 1
+          fi
+
+          # Common ones - only reached if the app check passes
+          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_OUTPUT
+          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_OUTPUT
+
+        # normal
       - uses: ./.github/actions/vercel-deploy
         with:
-          deployment_environment: ${{ inputs.deployment_environment }}
-          app_name: ${{ inputs.app_name }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          INTERNAL_NOTIFICATION_TOKEN: ${{ secrets.INTERNAL_NOTIFICATION_TOKEN }}
+          environment: ${{ inputs.environment }}
+          app: ${{ inputs.app }}
+          X_API_KEY_CI: ${{ secrets.X_API_KEY_CI }}
           VERCEL_TOKEN: ${{ steps.vercel-secrets.outputs.VERCEL_TOKEN }}
           VERCEL_ORG_ID: ${{ steps.vercel-secrets.outputs.VERCEL_ORG_ID }}
           VERCEL_PROJECT_ID: ${{ steps.vercel-secrets.outputs.VERCEL_PROJECT_ID }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
